# Generated by Django 4.2.8 on 2024-08-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('TURKISH', 'Turkish'), ('FOREIGN', 'Foreign')], max_length=10)),
                ('tckn', models.CharField(blank=True, max_length=11, null=True, verbose_name='TCKN')),
                ('passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Login.customer', verbose_name='Customer')),
            ],
        ),
    ]
