# Generated by Django 4.2.10 on 2024-08-05 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tckn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
