# Generated by Django 4.2.10 on 2024-08-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_sale_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
    ]
