# Generated by Django 4.2.10 on 2024-08-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_alter_tour_tour_day_title'),
        ('Login', '0010_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.item', verbose_name='Item'),
        ),
    ]
