# Generated by Django 4.2.10 on 2024-08-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_remove_sale_item_sale_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='tour',
            new_name='tours',
        ),
    ]
