# Generated by Django 4.2.10 on 2024-08-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0054_rename_tour_comment_tour'),
        ('Login', '0015_rename_tour_sale_tours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tours',
        ),
        migrations.AddField(
            model_name='sale',
            name='tours',
            field=models.ManyToManyField(to='Main.tour'),
        ),
    ]
