# Generated by Django 4.2.10 on 2024-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0016_remove_sale_tours_sale_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
