# Generated by Django 4.2.10 on 2024-08-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0017_sale_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='end_date',
        ),
    ]
