# Generated by Django 4.2.8 on 2024-08-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='activity_images/', verbose_name='Image')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='DayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='day_images/', verbose_name='Image')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='Image')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='item_images/', verbose_name='Image')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='museum_images/', verbose_name='Image')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/', verbose_name='Image')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='vehicle_icons/', verbose_name='Icon')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('TourImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.tourimage')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.activity')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.day')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.hotel')),
                ('item_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.itemimage')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.museum')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.vehicletype')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='DayImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.dayimage'),
        ),
    ]
