# Generated by Django 4.2.10 on 2024-08-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='TourImage',
        ),
        migrations.AddField(
            model_name='dayimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='item',
            name='TourImage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.tourimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourimage',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(choices=[('adana', 'Adana'), ('adıyaman', 'Adıyaman'), ('afyonkarahisar', 'Afyonkarahisar'), ('ağrı', 'Ağrı'), ('amasya', 'Amasya'), ('ankara', 'Ankara'), ('antalya', 'Antalya'), ('artvin', 'Artvin'), ('aydin', 'Aydın'), ('balıkesir', 'Balıkesir'), ('bilecik', 'Bilecik'), ('bingöl', 'Bingöl'), ('bitlis', 'Bitlis'), ('bolu', 'Bolu'), ('burdur', 'Burdur'), ('bursa', 'Bursa'), ('çanakkale', 'Çanakkale'), ('çankırı', 'Çankırı'), ('çorum', 'Çorum'), ('denizli', 'Denizli'), ('diyarbakır', 'Diyarbakır'), ('düzce', 'Düzce'), ('edirne', 'Edirne'), ('elazığ', 'Elazığ'), ('erzincan', 'Erzincan'), ('erzurum', 'Erzurum'), ('eskişehir', 'Eskişehir'), ('gaziantep', 'Gaziantep'), ('giresun', 'Giresun'), ('gümüşhane', 'Gümüşhane'), ('hakkari', 'Hakkari'), ('hatay', 'Hatay'), ('ısparta', 'Isparta'), ('istanbul', 'İstanbul'), ('izmir', 'İzmir'), ('kahramanmaraş', 'Kahramanmaraş'), ('karabük', 'Karabük'), ('karaman', 'Karaman'), ('kars', 'Kars'), ('kastamonu', 'Kastamonu'), ('kayseri', 'Kayseri'), ('kırıkkale', 'Kırıkkale'), ('kırklareli', 'Kırklareli'), ('kırşehir', 'Kırşehir'), ('klise', 'Kilis'), ('kocaeli', 'Kocaeli'), ('konya', 'Konya'), ('kütahya', 'Kütahya'), ('malatya', 'Malatya'), ('manisa', 'Manisa'), ('mardin', 'Mardin'), ('mersin', 'Mersin'), ('muğla', 'Muğla'), ('muş', 'Muş'), ('nevşehir', 'Nevşehir'), ('nigde', 'Niğde'), ('ordu', 'Ordu'), ('osmaniye', 'Osmaniye'), ('rize', 'Rize'), ('sakarya', 'Sakarya'), ('samsun', 'Samsun'), ('siirt', 'Siirt'), ('sinop', 'Sinop'), ('sivas', 'Sivas'), ('şanlıurfa', 'Şanlıurfa'), ('şırnak', 'Şırnak'), ('tekirdağ', 'Tekirdağ'), ('tokat', 'Tokat'), ('trabzon', 'Trabzon'), ('tunceli', 'Tunceli'), ('uşak', 'Uşak'), ('van', 'Van'), ('yalova', 'Yalova'), ('yozgat', 'Yozgat'), ('zonguldak', 'Zonguldak')], max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
