# Generated by Django 4.2.10 on 2024-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_tour_tourimage_dayimage_name_item_tourimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default='', max_length=100, verbose_name='Tour Price'),
        ),
    ]
