# Generated by Django 4.2.10 on 2024-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_item_item_title_item_item_title_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(max_length=255, verbose_name='Item Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title_mini',
            field=models.CharField(max_length=255, verbose_name='Item Mini Title'),
        ),
    ]
