# Generated by Django 4.2.10 on 2024-08-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_item_item_detail_alter_item_item_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_detail',
            field=models.CharField(max_length=255, verbose_name='Item Detail'),
        ),
    ]
