# Generated by Django 4.2.10 on 2024-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_item_item_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_detail',
            field=models.TextField(verbose_name='Item Detail'),
        ),
    ]
