# Generated by Django 4.2.10 on 2024-08-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_remove_tourprogram_tour_day_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourprogram',
            name='tour_day',
            field=models.CharField(help_text='Gün Aralığı Giriniz örn:(Gün 1-2)', max_length=255, verbose_name='Tour Day'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour_day_detail',
            field=models.TextField(max_length=255, verbose_name='Tour Day Detail'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour_day_title',
            field=models.CharField(max_length=100, verbose_name='Tour Day Title'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour_program_mini_title',
            field=models.CharField(max_length=100, verbose_name='Tour Program Mini Title'),
        ),
        migrations.AlterField(
            model_name='tourprogram',
            name='tour_program_title',
            field=models.CharField(max_length=100, verbose_name='Tour Program Title'),
        ),
    ]
