# Generated by Django 4.2.10 on 2024-08-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_tourprogram_tour_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tour_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.tourprogram'),
        ),
    ]
