# Generated by Django 4.2.10 on 2024-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_tour_tour_day_first_tour_tour_day_first_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_day_first',
            field=models.CharField(max_length=255, verbose_name='Tour Day First'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_first_detail',
            field=models.TextField(max_length=255, verbose_name='Tour Day First Detail'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_first_title',
            field=models.CharField(max_length=100, verbose_name='Tour Day First Title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_fourth',
            field=models.CharField(max_length=255, verbose_name='Tour Day Fourth'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_fourth_detail',
            field=models.TextField(max_length=255, verbose_name='Tour Day Fourth Detail'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_fourth_title',
            field=models.CharField(max_length=100, verbose_name='Tour Day Fourth Title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_second',
            field=models.CharField(max_length=255, verbose_name='Tour Day Second'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_second_detail',
            field=models.TextField(max_length=255, verbose_name='Tour Day Second Detail'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_second_title',
            field=models.CharField(max_length=100, verbose_name='Tour Day Second Title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_third',
            field=models.CharField(max_length=255, verbose_name='Tour Day Third'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_third_detail',
            field=models.TextField(max_length=255, verbose_name='Tour Day Third Detail'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_day_third_title',
            field=models.CharField(max_length=100, verbose_name='Tour Day Third Title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_program_mini_title',
            field=models.CharField(max_length=100, verbose_name='Tour Program Mini Title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_program_title',
            field=models.CharField(max_length=100, verbose_name='Tour Program Title'),
        ),
    ]
