# Generated by Django 4.2.10 on 2024-08-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_tour_tour_day_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tour_day_first',
            new_name='tour_day',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tour_day_first_detail',
            new_name='tour_day_detail',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tour_day_first_title',
            new_name='tour_day_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_fourth',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_fourth_detail',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_fourth_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_second',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_second_detail',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_second_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_third',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_third_detail',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_third_title',
        ),
    ]
