# Generated by Django 4.2.10 on 2024-08-03 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_rename_tour_day_first_tour_tour_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_day_detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
