# Generated by Django 4.2.10 on 2024-08-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_alter_tour_tour_day_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_day',
        ),
    ]
