# Generated by Django 4.2.8 on 2024-08-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_remove_tour_tour_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('role', models.CharField(choices=[('Sale Manager', 'Sale Manager'), ('Co-Founder & CFO', 'Co-Founder & CFO'), ('Technical Lead & CTO', 'Technical Lead & CTO'), ('Marketing Manager', 'Marketing Manager')], max_length=255)),
                ('image', models.ImageField(upload_to='team_images/', verbose_name='Image')),
                ('content', models.CharField(max_length=100, verbose_name='content')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
