# Generated by Django 4.2.8 on 2024-08-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_teamsmodel_alter_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamsModel',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(default='', max_length=100, verbose_name='Tour Price'),
        ),
    ]
