# Generated by Django 4.2.10 on 2024-08-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0023_teamsmodel_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Main.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
