# Generated by Django 4.2.8 on 2024-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_activityimage_hotelimage_tour_başlık_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_day',
            field=models.IntegerField(default=1, help_text='Gün sayısını girin (1-7 arası)', verbose_name='Bitiş Günü'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='start_day',
            field=models.IntegerField(default=1, help_text='Gün sayısını girin (1-7 arası)', verbose_name='Başlangıç Günü'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi'),
        ),
    ]
