# Generated by Django 4.2.8 on 2024-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_item_end_day_item_start_day_alter_item_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='şehir'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='end_day',
            field=models.IntegerField(help_text='Gün sayısını girin', verbose_name='Bitiş Günü'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_day',
            field=models.IntegerField(help_text='Gün sayısını girin', verbose_name='Başlangıç Günü'),
        ),
        migrations.RemoveField(
            model_name='tour_başlık',
            name='item',
        ),
        migrations.AddField(
            model_name='tour_başlık',
            name='item',
            field=models.ManyToManyField(related_name='items', to='Main.item'),
        ),
    ]
