# Generated by Django 4.2.8 on 2024-08-08 11:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_item_location_alter_item_end_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tour_program_title', models.CharField(max_length=100, verbose_name='Tour Program Title')),
                ('tour_program_mini_title', models.CharField(max_length=100, verbose_name='Tour Program Mini Title')),
                ('tour_day_title', models.CharField(max_length=100, verbose_name='Tour Day Title')),
                ('tour_day_detail', ckeditor.fields.RichTextField()),
                ('is_delete', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_detail',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_day_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_program_mini_title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_program_title',
        ),
        migrations.RemoveField(
            model_name='tourimage',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tour_image', to='Main.tourimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='item',
            field=models.ManyToManyField(related_name='items', to='Main.item'),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tour_başlık',
        ),
    ]
