# Generated by Django 4.2.8 on 2024-08-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_tourimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourimage',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='TourImage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.tourimage'),
            preserve_default=False,
        ),
    ]
