# Generated by Django 4.2.8 on 2024-08-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_remove_tourimage_name_item_tourimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='TourImage',
        ),
    ]
