# Generated by Django 4.2.8 on 2024-08-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_tourimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Tour_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Main.tour_detail'),
            preserve_default=False,
        ),
    ]
