# Generated by Django 4.2.8 on 2024-08-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0040_tour_tour_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Tour_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tour_detail', to='Main.tour_detail'),
        ),
    ]
