# Generated by Django 4.2.8 on 2024-08-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0041_alter_tour_tour_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_detail',
            name='tour_day_detail',
        ),
        migrations.RemoveField(
            model_name='tour_detail',
            name='tour_day_title',
        ),
    ]
