# Generated by Django 4.2.8 on 2024-08-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0042_remove_tour_detail_tour_day_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_detail',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
