# Generated by Django 4.2.8 on 2024-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0044_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirimli Fiyat'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gün'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Tarihi'),
        ),
    ]
