# Generated by Django 4.2.8 on 2024-08-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0046_remove_comment_item_comment_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_detail',
            name='details',
            field=models.CharField(default=1, max_length=100, verbose_name='details'),
            preserve_default=False,
        ),
    ]
