# Generated by Django 4.2.8 on 2024-08-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0047_tour_detail_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_detail',
            name='tour_program_mini_title',
            field=models.TextField(max_length=100, verbose_name='Tour Program Mini Title'),
        ),
    ]
