# Generated by Django 4.2.8 on 2024-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0048_alter_tour_detail_tour_program_mini_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_detail',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour_detail',
            name='tour_program_mini_title',
            field=models.CharField(max_length=100, verbose_name='Tour Program Mini Title'),
        ),
    ]
