# Generated by Django 4.2.8 on 2024-08-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0049_alter_tour_detail_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='item',
            field=models.ManyToManyField(related_name='tours', to='Main.item'),
        ),
    ]
