# Generated by Django 4.2.8 on 2024-08-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0051_tour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
    ]
