# Generated by Django 4.2.10 on 2024-08-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0053_tour_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Tour',
            new_name='tour',
        ),
    ]
